/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import core.Producto;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Namithia
 */
public class EliminarArticulo extends javax.swing.JDialog {

    /**
     * Creates new form EliminarArticulo
     */
    
    Producto p=null;
    Image imagen = null;
    int x=0, y=0;
    
    
    public EliminarArticulo(java.awt.Frame parent, boolean modal) throws IOException {
        super(parent, modal);
        initComponents();
           
        Econfirmacion.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ecodbarras = new javax.swing.JLabel();
        Tcodbarras = new javax.swing.JTextField();
        Tnombre = new javax.swing.JTextField();
        Enombre = new javax.swing.JLabel();
        Eprecio = new javax.swing.JLabel();
        Tprecio = new javax.swing.JTextField();
        Beliminar = new javax.swing.JButton();
        Bcerrar = new javax.swing.JButton();
        Bbusqueda = new javax.swing.JButton();
        Tbusqueda = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        canvas1 = new java.awt.Canvas();
        Econfirmacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        Ecodbarras.setText("Cod_Barras:");

        Tcodbarras.setEditable(false);

        Tnombre.setEditable(false);

        Enombre.setText("Nombre:");

        Eprecio.setText("Precio:");

        Tprecio.setEditable(false);

        Beliminar.setText("Eliminar");
        Beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeliminarActionPerformed(evt);
            }
        });

        Bcerrar.setText("Cerrar");
        Bcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcerrarActionPerformed(evt);
            }
        });

        Bbusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/16px/search.png"))); // NOI18N
        Bbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbusquedaActionPerformed(evt);
            }
        });

        Tbusqueda.setForeground(new java.awt.Color(153, 153, 153));
        Tbusqueda.setText("Búsqueda");
        Tbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbusquedaActionPerformed(evt);
            }
        });
        Tbusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TbusquedaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TbusquedaFocusLost(evt);
            }
        });
        Tbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TbusquedaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TbusquedaKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        canvas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvas1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Econfirmacion.setText("Eliminacion Correcta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Bbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Ecodbarras)
                                    .addComponent(Eprecio)
                                    .addComponent(Enombre))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Tnombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tcodbarras, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Beliminar)
                                .addGap(42, 42, 42)
                                .addComponent(Bcerrar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Econfirmacion)
                                .addGap(39, 39, 39)))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Tbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bbusqueda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ecodbarras)
                            .addComponent(Tcodbarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Enombre)
                            .addComponent(Tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Eprecio)
                            .addComponent(Tprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Beliminar)
                            .addComponent(Bcerrar))
                        .addGap(25, 25, 25)
                        .addComponent(Econfirmacion))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcerrarActionPerformed
       
        this.dispose();
        
    }//GEN-LAST:event_BcerrarActionPerformed

    private void BbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbusquedaActionPerformed
       
        Econfirmacion.setVisible(false);
        
        if (!Tbusqueda.getText().equals("") || Tbusqueda.getText().equals("Búsqueda")) {

            try {
                p = new Producto(Integer.parseInt(Tbusqueda.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(EstadoStock.class.getName()).log(Level.SEVERE, null, ex);
            }

            Tcodbarras.setText(String.valueOf(p.getCod_barras()));
            Tnombre.setText(p.getNombre());
            Tprecio.setText(String.valueOf(p.getPrecio()));
                        
            String ruta="Imagenes/" + p.getCod_barras() + ".jpg";
           
    imagen = new ImageIcon(ruta).getImage();

            Graphics g = canvas1.getGraphics();

            x = imagen.getWidth(null);
            y = imagen.getHeight(null);


            if (x > canvas1.getWidth() || y > canvas1.getHeight()) {

                if (x > y) {
                    imagen = imagen.getScaledInstance(canvas1.getWidth(), -1, Image.SCALE_DEFAULT);
                    x = 0;
                    y = (canvas1.getHeight() - y) / 2;

                } else {
                    imagen = imagen.getScaledInstance(-1, canvas1.getHeight(), Image.SCALE_DEFAULT);
                    x = (canvas1.getWidth() - x) / 2;
                    y = 0;
                }
            } 
            else {
                
                x = (canvas1.getWidth() - x) / 2;
                y = (canvas1.getHeight() - y) / 2;
                
            }
            g.drawImage(imagen, x, y, null);
            


        }
        
    }//GEN-LAST:event_BbusquedaActionPerformed

    private void TbusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TbusquedaKeyPressed
       
        if (evt.getKeyCode() == evt.VK_ENTER) {

            Bbusqueda.doClick();

        }
        
    }//GEN-LAST:event_TbusquedaKeyPressed

    private void TbusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TbusquedaKeyTyped
    

    }//GEN-LAST:event_TbusquedaKeyTyped

    private void TbusquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TbusquedaFocusLost

    }//GEN-LAST:event_TbusquedaFocusLost

    private void BeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliminarActionPerformed
        
        if(p!=null){
            Producto.borrarDB(p.getCod_barras());
            Econfirmacion.setVisible(true);
            p=null;
        }
        else{
            Toolkit.getDefaultToolkit().beep();
        }
        
    }//GEN-LAST:event_BeliminarActionPerformed

    private void TbusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TbusquedaFocusGained
        
        if(Tbusqueda.getText().equals("Búsqueda")){
            Tbusqueda.setText(null);
            Tbusqueda.setForeground(Color.black);
        }

        
    }//GEN-LAST:event_TbusquedaFocusGained

    private void TbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TbusquedaActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        
        
        
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        canvas1.getGraphics().drawImage(imagen, x, y, null);        
    }//GEN-LAST:event_formWindowGainedFocus

    private void canvas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvas1MouseClicked
        canvas1.getGraphics().drawImage(imagen, x, y, null);       
    }//GEN-LAST:event_canvas1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EliminarArticulo dialog=null;
                try {
                    dialog = new EliminarArticulo(new javax.swing.JFrame(), true);
                } catch (IOException ex) {
                    Logger.getLogger(EliminarArticulo.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bbusqueda;
    private javax.swing.JButton Bcerrar;
    private javax.swing.JButton Beliminar;
    private javax.swing.JLabel Ecodbarras;
    private javax.swing.JLabel Econfirmacion;
    private javax.swing.JLabel Enombre;
    private javax.swing.JLabel Eprecio;
    private javax.swing.JTextField Tbusqueda;
    private javax.swing.JTextField Tcodbarras;
    private javax.swing.JTextField Tnombre;
    private javax.swing.JTextField Tprecio;
    private java.awt.Canvas canvas1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}